  version: '3.7'

  services:
    proxy:
      image: nginx:latest
    ports:
      - 80:80
      - 443:443
    env_file:
      - proxy.env
    command: sh -c "/etc/nginx/build-conf.sh && nginx -g 'daemon off;'"
